# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnectingFireBase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConnectingFireBase
  pod 'Firebase/Core'
  pod 'Firebase'
  pod 'Firebase/Database’
  pod 'Firebase/Storage'
  pod 'Firebase/Auth’

  target 'ConnectingFireBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConnectingFireBaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
